### ISSUE TITLE
Make plot URLs more easily hackable

### ISSUE THREAD

**Issue by BigLep** [plprobelab/website#56]
If I am given a link to https://probelab.io/websites/blog.ipfs.tech/#website-snapshot-performance-gauge-blogipfstech-kubo , in order to quickly "hack" the URL for another site, I need to change both the path AND the anchor.  I'd ideally only like to change the path.

```diff
-https://probelab.io/websites/blog.ipfs.tech/#website-snapshot-performance-gauge-blogipfstech-kubo
+https://probelab.io/websites/blog.ipfs.tech/#website-snapshot-performance-gauge-kubo
```

For example, if I want to go from blog.ipfs.tech link to docs.ipfs.tech I only have to change one thing that way:

```diff
-https://probelab.io/websites/blog.ipfs.tech/#website-snapshot-performance-gauge-kubo
+https://probelab.io/websites/docs.ipfs.tech/#website-snapshot-performance-gauge-kubo
```

**Comment by iand** [comment]
@BigLep can you confirm you only see this as a problem in the website section, because the name of the website is duplicated?

**Comment by BigLep** [comment]
@iand : yeah, I only noticed in in the "website" section.  Thanks for the fix!
