### ISSUE TITLE
Add "suggest a change to this page" link/action

### ISSUE THREAD

**Issue by BigLep** [plprobelab/website#61]
I think we want to encourage people to submit changes/feedback to the site.  Giving someone a direct link to modify the corresponding markdown file could be nice.

I have no idea of the actual usage, but docs.ipfs.tech has it

<img width="807" alt="image" src="https://github.com/plprobelab/website/assets/85411/8011db6b-eb98-4596-997b-83a6bc2698a5">

**Comment by iand** [comment]
This was implemented and deployed by https://github.com/plprobelab/website/pull/62
